### PR TITLE
Make the result comment optional

### PR DESCRIPTION
**Pull request by ikerexxe**

### CODE REVIEW

**Comment by ikerexxe** [comment]
I'm not an expert in GO so please review with care as I may have inadvertently made a very big mistake.

**Comment by myml** [comment]
What do you want to achieve? If you do not want to send the check result to commit, Should have skipped here https://github.com/linuxdeepin/action-cppcheck/blob/fab2b612ccb9f4c811086a5609e719a6bfb0558f/cmd/action-cppcheck/main.go#L126-L134

Maybe code -1 should be used to make the action fail?

**Comment by ikerexxe** [comment]
I'd like to remove only the check result, as an example: https://github.com/SSSD/sssd/pull/6089#pullrequestreview-927578085. I'd like to keep the errors themselves being published on the PR. I think that your proposal would also remove those. Am I right?

**Comment by myml** [comment]
Do you want to delete outdated comments or not send any comments?
The Go Program is written for posting comments. if you do not need comment, can use the workflow
```yaml
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: sudo apt install -y cppcheck
      - name: run
        run: cppcheck --enable=all --error-exitcode=-1 ./ 1>/dev/null
```

**Comment by ikerexxe** [comment]
> Do you want to delete outdated comments or not send any comments? The Go Program is written for posting comments. if you do not need comment, can use the workflow
> 
> ```yaml
>     steps:
>       - uses: actions/checkout@v3
>       - name: install
>         run: sudo apt install -y cppcheck
>       - name: run
>         run: cppcheck --enable=all --error-exitcode=-1 ./ 1>/dev/null
> ```

It's not clear for me that you are understanding what I'm trying to fix so I'd like to clarify it further.

This action posts two types of comments: the errors detected by cppcheck and the final result (Good or improvements are needed). I'd like the action to continue posting the errors detected by cppcheck, but I'd like to make the posting of the final result configurable. This way, I can configure it to disable the posting of the result for some workflows.

**Comment by myml** [comment]
https://github.com/myml/action-cppcheck/commit/25df296b56ec1345cbc19d66b733040a50bbe286
I modified the action.yam file to achieve it, it is what you want?

Test results [here](https://github.com/myml/test/pulls)

**Comment by ikerexxe** [comment]
> [myml@25df296](https://github.com/myml/action-cppcheck/commit/25df296b56ec1345cbc19d66b733040a50bbe286) I modified the action.yam file to achieve it, it is what you want?

No, but it's good that your provided the test results because it will enable me to explain myself correctly.

I don't want the tool to post the [final result comment](https://github.com/myml/test/pull/3#pullrequestreview-932704854). But I want the tool to post the [errors detected](https://github.com/myml/test/pull/3#discussion_r843399289).

**Comment by myml** [comment]
I get it. This code is ok.

**Comment by ikerexxe** [comment]
Thank you for taking care of it!

**Comment by myml** [comment]
Hi @ikerexxe ! I forgot one thing. If  comment_result is set to false and code checks out ok, then there is no need to call CreateReview agent. 
Unable to create a review without 'body' and 'comments'

**Comment by ikerexxe** [comment]
> Unable to create a review without 'body' and 'comments'

Is this an error message from the action?

**Comment by myml** [comment]
See https://github.com/myml/test/pull/3

**Comment by myml** [comment]
Error from github api
```
2022/04/08 07:22:01 POST https://api.github.com/repos/myml/test/pulls/3/reviews: 422 Unprocessable Entity [{Resource: Field: Code: Message:You need to leave a comment indicating the requested changes.}]
```

**Comment by ikerexxe** [comment]
I've opened a new [PR](https://github.com/linuxdeepin/action-cppcheck/pull/11) to fix this issue.

**Pull request merged**
